DEVICE_CLASSES = (
    'ac_frequency', 'action', 'action_group', 'angle', 'angle_axis', 'aqi', 'auto_lock', 'auto_relock_time',
    'away_mode', 'away_preset_days', 'away_preset_temperature', 'battery', 'battery_low', 'battery_voltage',
    'boost_time', 'button_lock', 'carbon_monoxide', 'child_lock', 'co2', 'co', 'comfort_temperature',
    'consumer_connected', 'contact', 'cover_position', 'cover_position_tilt', 'cover_tilt', 'cpu_temperature',
    'cube_side', 'current', 'current_phase_b', 'current_phase_c', 'deadzone_temperature', 'device_temperature', 'eco2',
    'eco_mode', 'eco_temperature', 'effect', 'energy', 'fan', 'flip_indicator_light', 'force', 'formaldehyd', 'gas',
    'hcho', 'holiday_temperature', 'humidity', 'illuminance', 'illuminance_lux', 'brightness_state', 'keypad_lockout',
    'led_disabled_night', 'light_brightness', 'light_brightness_color', 'light_brightness_colorhs',
    'light_brightness_colortemp', 'light_brightness_colortemp_color', 'light_brightness_colortemp_colorhs',
    'light_brightness_colortemp_colorxy', 'light_brightness_colorxy', 'light_colorhs', 'linkquality',
    'local_temperature', 'lock', 'lock_action', 'lock_action_source_name', 'lock_action_source_user', 'max_temperature',
    'max_temperature_limit', 'min_temperature', 'noise', 'noise_detected', 'occupancy', 'occupancy_level',
    'open_window', 'open_window_temperature', 'pm10', 'pm25', 'position', 'power', 'power_factor', 'power_apparent',
    'power_on_behavior', 'power_outage_count', 'power_outage_memory', 'presence', 'pressure',
    'programming_operation_mode', 'smoke', 'soil_moisture', 'sos', 'sound_volume', 'switch', 'switch_type',
    'switch_type_2', 'tamper', 'temperature', 'test', 'valve_position', 'valve_switch', 'valve_state',
    'valve_detection', 'vibration', 'voc', 'voltage', 'voltage_phase_b', 'voltage_phase_c', 'water_leak', 'warning',
    'week', 'window_detection', 'moving', 'x_axis', 'y_axis', 'z_axis', 'pincode', 'squawk','state')